### ISSUE TITLE
User Experience Punchlist

### ISSUE THREAD

**Issue by danking** [vortex-data/vortex#1072]
In Progress:

Short term:

- [ ] Teach `PyArray` `__getitem__` which just delegates to `scalar_at`.
- [x] Teach PyVortex to use parallelism during decompression.
- [x] Make reading a Vortex file into an Arrow Array as fast as Parquet (~~at least partly needs to address read/write disagreement on chunk size, see below~~ we side stepped this by removing buffer sizes when implementing filter pushdown).
- [ ] Make reading a Vortex file with Polars as fast as Parquet. https://github.com/spiraldb/vortex/issues/1071
- [x] `read` should have high throughput on files written by `write` (~~currently, write does not enforce chunking whereas read does which can degrade throughput on arrays for which slice is not free~~ again, sidestepped by removing buffer sizing from filter pushdown).
- [ ] (docs) Write a comparison section which describes similarities and differences from other file formats.
- [x] Expose Vortex compute methods in Python API by way of new classes (e.g. `Array.as_struct()` and `StructArray` which permits column selection).
- [ ] Teach Vortex IsNull & IsNotNull and plumb substrait into them.
- [x] Do not expose modules with confusing names such as `vortex.encoding`.
- [ ] Expose more functions on scalar values such as `__eq__`, array indexing, or getting a `memoryview`.
- [x] Teach PyVortex (really: Layout readers and writers) to read/write non-struct arrays.
- [ ] Teach RecordBatchReader to read from multiple files.
- [ ] Teach Polars to write Vortex files.
- [ ] Teach DuckDB to write Vortex files.
- [ ] Support multiple files and/or directories in the Vortex Dataset API
- [ ] Consider using the Rufo theme for the docs

Long term:

- [ ] For Torch, expose a method to read from a Vortex file directly into a mutable NumPy array. Torch does not support immutable NumPy arrays.
- [ ] Reduce Vortex array metadata size. This primarily benefits very small datasets (e.g. PBI AirlineSentiment).
- [ ] Implement a RecordBatchReader for Vortex arrays and Vortex files.
- [ ] Implement a Pandas ExtensionArray which permits compute on the compressed array representations (thus avoiding the cost of decompression).
- [ ] Integrate with DuckDB.
- [ ] (docs) Finish specification and move into docs.

Complete:
- [x] Pushdown row filters https://github.com/spiraldb/vortex/pull/1124 .
- [x] (docs) Write a Vortex quick start which demonstrates read, write, compress, and integration with pandas, polars, arrow, and duckdb. https://github.com/spiraldb/vortex/pull/1137
- [x] (docs) Move current documentation into an API Reference section. https://github.com/spiraldb/vortex/pull/1137
- [x] (docs) Write (or gather from Notion & Docs) an enduser-friendly explanation of the Vortex file format. https://github.com/spiraldb/vortex/pull/1137
- [x] `write` should either warn or compress by default so that naive users understand why `write(vortex.array(...), ...)` gives no benefit. https://github.com/spiraldb/vortex/pull/1137
- [x] Teach PyVortex to read from Object Storage. #1151 
- [x] Teach `PyArray` `scalar_at` ([requested by Rob](https://github.com/spiraldb/vortex/pull/1083#discussion_r1806280681)) https://github.com/spiraldb/vortex/pull/1095.
- [x] Disable ~~or fix~~ RoaringIntArray and RoaringBoolArray to be no-copy. https://github.com/spiraldb/vortex/issues/1075, https://github.com/spiraldb/vortex/pull/1076
- [x] Remove Vortex "cannot find compressor" log statements when calling `compress`. https://github.com/spiraldb/vortex/pull/1089
- [x] Implement the Arrow Dataset API https://github.com/spiraldb/vortex/pull/1089

**Comment by gatesn** [comment]
Going to close this out as largely completed! The remaining relevant follow ups are mostly tracked, or else we can re-open.
